spring:
  datasource:
    url: jdbc:mysql://localhost:3306/continent?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8&createDatabaseIfNotExist=true

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
#Override
Spring.main.allow-beand-definition-overriding=true
server:
  port: 8080
